[package]
name = "advent_of_code_2025"
version = "0.1.0"
edition = "2021"

[lib]
name = "advent_of_code_2025"
path = "src/lib.rs"

[[bin]]
name = "advent_of_code_2025"
path = "src/main.rs"

[dependencies]
